name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all


    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload built Foss apk
      uses: actions/upload-artifact@v4
      with:
          name: APK
          path: ${{ github.workspace }}/app/build/outputs/apk/debug
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v2.20240731"
          prerelease: true
          title: "v2-20240731 (dev)"
          files: |
            ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
